# Generated by Django 6.0 on 2026-01-15 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('lead_manager', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ipo',
            options={'ordering': ['-open_date']},
        ),
        migrations.AddField(
            model_name='ipo',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='debt_to_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='lead_manager',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='ipo',
            name='listing_at',
            field=models.CharField(default='NSE', max_length=50),
        ),
        migrations.AddField(
            model_name='ipo',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='roa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='volatility',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('min_investment', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('max_investment', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('preferred_sectors', models.CharField(blank=True, help_text='Comma-separated sectors', max_length=500)),
                ('risk_tolerance', models.IntegerField(default=5, help_text='1-10, where 1 is very conservative and 10 is very aggressive', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('years_investing', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('growth_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('rationale', models.TextField(help_text='Why this recommendation was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ipo.investorprofile')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ipo.ipo')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('investor_profile', 'ipo')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocation', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('expected_return', models.FloatField(default=0.0)),
                ('portfolio_risk', models.FloatField(default=0.0)),
                ('diversification_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_recommendation', to='ipo.investorprofile')),
                ('top_recommendations', models.ManyToManyField(related_name='in_portfolios', to='ipo.recommendation')),
            ],
        ),
    ]
