# Generated by Django 6.0 on 2026-01-26 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0003_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='debt_to_equity',
        ),
        migrations.AddField(
            model_name='ipo',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='revenue_growth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='preferred_sectors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='risk_tolerance',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='roa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='volatility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='confidence_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rationale',
            field=models.TextField(),
        ),
    ]
