# Generated by Django 6.0 on 2026-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0004_remove_ipo_debt_to_equity_ipo_pe_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol/ticker', max_length=20, null=True),
        ),
    ]
