# Generated by Django 5.0.6 on 2026-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0005_ipo_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
