# Generated by Django 5.0.6 on 2026-02-18 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0006_recommendation_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='brand_moat',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ipo',
            name='esg_score',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ipo',
            name='management_quality',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='human_insight',
            field=models.TextField(blank=True, help_text='A more personal, advisor-like explanation', null=True),
        ),
    ]
