# Generated by Django 5.0.6 on 2026-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0007_ipo_brand_moat_ipo_esg_score_ipo_management_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='investment_horizon',
            field=models.CharField(choices=[('short', 'Short-term'), ('medium', 'Medium-term'), ('long', 'Long-term')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='ipo',
            name='debt_to_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='price_band_lower',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='price_band_upper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
