# Generated by Django 5.2.17 on 2026-08-24 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0009_expand_investor_personas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SavedPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('investor_persona', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate / Balanced'), ('balanced', 'Balanced'), ('growth', 'Growth'), ('aggressive', 'Aggressive')], max_length=20)),
                ('optimization_method', models.CharField(max_length=40)),
                ('allocations', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
